# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:               ROLE_USER
        ROLE_SUPER_ADMIN:         ROLE_ADMIN
        ROLE_AUTHOR:              ROLE_USER
        ROLE_MEMBER:              ROLE_MEMBER
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                    role: ROLE_NONE }
        - { path: ^/resetting,                   role: ROLE_NONE }
        - { path: ^/,                           role: ROLE_USER }
        - { path: ^/author,                      role: ROLE_AUTHOR }
        - { path: ^/admin,                       role: ROLE_ADMIN }
        - { path: ^/author,                      role: ROLE_AUTHOR }


